// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StartInternalRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StartInternalRequest)
    com.google.protobuf.MessageOrBuilder {
}
