// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StartInternalResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StartInternalResponse)
    com.google.protobuf.MessageOrBuilder {
}
