// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StartRequest)
    com.google.protobuf.MessageOrBuilder {
}
