// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StartResponse)
    com.google.protobuf.MessageOrBuilder {
}
