// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StopResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StopResponse)
    com.google.protobuf.MessageOrBuilder {
}
