// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface StopRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.StopRequest)
    com.google.protobuf.MessageOrBuilder {
}
