// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public final class Vote {
  private Vote() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_VoteResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StartInternalRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StartInternalRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StartInternalResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StartInternalResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StopRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StopRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_StopResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_StopResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_VoteStatusRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_VoteStatusRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_protos_VoteStatusResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_protos_VoteStatusResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nvote.proto\022\006protos\".\n\013VoteRequest\022\021\n\tp" +
      "erson_id\030\001 \001(\005\022\014\n\004vote\030\002 \001(\005\" \n\014VoteResp" +
      "onse\022\020\n\010greeting\030\001 \001(\t\"\016\n\014StartRequest\"\017" +
      "\n\rStartResponse\"\026\n\024StartInternalRequest\"" +
      "\027\n\025StartInternalResponse\"\r\n\013StopRequest\"" +
      "\016\n\014StopResponse\"\023\n\021VoteStatusRequest\"\024\n\022" +
      "VoteStatusResponse2\360\002\n\013VoteService\022<\n\017ad" +
      "dVoteInternal\022\023.protos.VoteRequest\032\024.pro" +
      "tos.VoteResponse\022=\n\016startElections\022\024.pro" +
      "tos.StartRequest\032\025.protos.StartResponse\022" +
      "U\n\026startElectionsInternal\022\034.protos.Start" +
      "InternalRequest\032\035.protos.StartInternalRe" +
      "sponse\022=\n\020stopVoteInternal\022\023.protos.Stop" +
      "Request\032\024.protos.StopResponse\022N\n\025getVote" +
      "StatusInternal\022\031.protos.VoteStatusReques" +
      "t\032\032.protos.VoteStatusResponseB\002P\001b\006proto" +
      "3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_protos_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_protos_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_VoteRequest_descriptor,
        new java.lang.String[] { "PersonId", "Vote", });
    internal_static_protos_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_protos_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_VoteResponse_descriptor,
        new java.lang.String[] { "Greeting", });
    internal_static_protos_StartRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_protos_StartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StartRequest_descriptor,
        new java.lang.String[] { });
    internal_static_protos_StartResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_protos_StartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StartResponse_descriptor,
        new java.lang.String[] { });
    internal_static_protos_StartInternalRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_protos_StartInternalRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StartInternalRequest_descriptor,
        new java.lang.String[] { });
    internal_static_protos_StartInternalResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_protos_StartInternalResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StartInternalResponse_descriptor,
        new java.lang.String[] { });
    internal_static_protos_StopRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_protos_StopRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StopRequest_descriptor,
        new java.lang.String[] { });
    internal_static_protos_StopResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_protos_StopResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_StopResponse_descriptor,
        new java.lang.String[] { });
    internal_static_protos_VoteStatusRequest_descriptor =
      getDescriptor().getMessageTypes().get(8);
    internal_static_protos_VoteStatusRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_VoteStatusRequest_descriptor,
        new java.lang.String[] { });
    internal_static_protos_VoteStatusResponse_descriptor =
      getDescriptor().getMessageTypes().get(9);
    internal_static_protos_VoteStatusResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_protos_VoteStatusResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
