// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface VoteStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.VoteStatusRequest)
    com.google.protobuf.MessageOrBuilder {
}
