// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 person_id = 1;</code>
   */
  int getPersonId();

  /**
   * <code>int32 vote = 2;</code>
   */
  int getVote();
}
