// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vote.proto

package protos;

public interface VoteStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:protos.VoteStatusResponse)
    com.google.protobuf.MessageOrBuilder {
}
